//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Контракт генерации сообщений с именем fam из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchStudent", ReplyAction="*")]
        Client.ServiceReference1.SearchStudentResponse SearchStudent(Client.ServiceReference1.SearchStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.SearchStudentResponse> SearchStudentAsync(Client.ServiceReference1.SearchStudentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchStudent", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.SearchStudentRequestBody Body;
        
        public SearchStudentRequest() {
        }
        
        public SearchStudentRequest(Client.ServiceReference1.SearchStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subname;
        
        public SearchStudentRequestBody() {
        }
        
        public SearchStudentRequestBody(string fam, string subname) {
            this.fam = fam;
            this.subname = subname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.SearchStudentResponseBody Body;
        
        public SearchStudentResponse() {
        }
        
        public SearchStudentResponse(Client.ServiceReference1.SearchStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchStudentResult;
        
        public SearchStudentResponseBody() {
        }
        
        public SearchStudentResponseBody(string SearchStudentResult) {
            this.SearchStudentResult = SearchStudentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Client.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Client.ServiceReference1.WebService1Soap>, Client.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.SearchStudentResponse Client.ServiceReference1.WebService1Soap.SearchStudent(Client.ServiceReference1.SearchStudentRequest request) {
            return base.Channel.SearchStudent(request);
        }
        
        public string SearchStudent(string fam, string subname) {
            Client.ServiceReference1.SearchStudentRequest inValue = new Client.ServiceReference1.SearchStudentRequest();
            inValue.Body = new Client.ServiceReference1.SearchStudentRequestBody();
            inValue.Body.fam = fam;
            inValue.Body.subname = subname;
            Client.ServiceReference1.SearchStudentResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).SearchStudent(inValue);
            return retVal.Body.SearchStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.SearchStudentResponse> Client.ServiceReference1.WebService1Soap.SearchStudentAsync(Client.ServiceReference1.SearchStudentRequest request) {
            return base.Channel.SearchStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.SearchStudentResponse> SearchStudentAsync(string fam, string subname) {
            Client.ServiceReference1.SearchStudentRequest inValue = new Client.ServiceReference1.SearchStudentRequest();
            inValue.Body = new Client.ServiceReference1.SearchStudentRequestBody();
            inValue.Body.fam = fam;
            inValue.Body.subname = subname;
            return ((Client.ServiceReference1.WebService1Soap)(this)).SearchStudentAsync(inValue);
        }
    }
}
